Vagrant.configure("2") do |config|
config.vm.define :test_vm do |test_vm|
test_vm.vm.box = "centos/7"
test_vm.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end
test_vm.vm.network :private_network, :ip => '192.168.112.1'
config.vm.provider :libvirt do |libvirt|
libvirt.driver = "kvm"
libvirt.connect_via_ssh = false
end
end
end

